### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by ilovetogetspamed** [vsoch/svgtools#1]
System stuff:

```
macOS Mojave 10.14.6 (18G4032)
svgpathtools==1.3.3
Python 3.7.5 (v3.7.5:5c02a39a0b, Oct 14 2019, 18:49:57) 
[Clang 6.0 (clang-600.0.57)] on darwin
```

Code:
```python

# create svgpathtools Path objects from an SVG file
f = 'Panel Wall Scenes 9.svg'
print(f)
paths, attributes = svg2paths(f)

for n in range(len(paths)):
    # print(attributes[n])

    # Let's find its length
    plength = paths[n].length()
    pid = attributes[n]['id']
    # print(f"id: {pid} length = {length}")

    # Find height, width
    xmin, xmax, ymin, ymax = paths[n].bbox()
    pwidth = xmax - xmin
    pheight = ymax - ymin

    # save result to mypaths
    vid = {plength: pid}

    print(f"ID: {pid} length = {plength} width = {pwidth} height = {pheight}")
```

Results in:

```
Panel Wall Scenes 9.svg
Traceback (most recent call last):
  File "fill_svg_db.py", line 54, in <module>
    plength = paths[n].length()
  File "/Library/Python/3.7/lib/python/site-packages/svgpathtools/path.py", line 1870, in length
    self._calc_lengths(error=error, min_depth=min_depth)
  File "/Library/Python/3.7/lib/python/site-packages/svgpathtools/path.py", line 1847, in _calc_lengths
    self._lengths = [each/self._length for each in lengths]
  File "/Library/Python/3.7/lib/python/site-packages/svgpathtools/path.py", line 1847, in <listcomp>
    self._lengths = [each/self._length for each in lengths]
ZeroDivisionError: float division by zero
```

Files:

This one throws the error: [Panel Wall Scenes 9.svg.txt](https://github.com/vsoch/svgtools/files/4529652/Panel.Wall.Scenes.9.svg.txt)

This one works OK: [Panel Wall Scenes 10.svg.txt](https://github.com/vsoch/svgtools/files/4529675/Panel.Wall.Scenes.10.svg.txt)

** Note: rename file to use in code.

If you open the files in Gimp they look empty because stroke-width:0.34999999 is a very small stroke.  Change to one if you want to see the outline.  For my purposes I don't need to see the image.

**Comment by vsoch** [comment]
I think you possibly posted to the wrong library? svg2path is for svgpathtools, not svgtools. I think you want this repo: https://github.com/mathandy/svgpathtools?

**Comment by vsoch** [comment]
Closing issue, opened on wrong repository.
